language: en
country_profile:
    iso3: GUY
    website: null
    logo: ./assets/img/GUYlogo.png
    timezone: America/Guyana 

openfismis: 
    dbi:
        drv: MariaDB
        dbname: guycalipseo
        host: localhost
        port: 3306
        user: root
        password: root
    
structure:
    home:
        title: Home page
    vessels:
        title: Vessels dashboard
    individuals: 
        title: Individual dashboard
    logbooks:
        title: Logbooks dashboard
    artfish:
        title: Artfish
    statistics:
        title: Statistics
    
modules:
    vessel_list:
        title: Vessels register
        icon: table
    vessel_breakdown:
        title: Vessels breakdown
        icon: ship
    vessel_qa:
        title: Vessels quality assessment
        icon: ship
    individual_list: 
        title: Individual list
    artfish_overview:
      enabled: TRUE
    artfish_report:
      enabled: TRUE
    artfish_species:
      enabled: TRUE
    artfish_fishing_unit:
      enabled: TRUE    

    