language: en
country_profile:
    iso3: SUR
    website: http://lvv.gov.sr
    logo: ./assets/img/SURlogo.png
    timezone: America/Paramaribo 

openfismis: 
    dbi:
        drv: MariaDB
        dbname: ttocalipseo
        host: $HOST
        port: 3306
        user: $USERNAME
        password: $PASSWORD
    
structure:
    home:
        title: Home page
    vessels:
        title: Vessels dashboard
    individuals: 
        title: Individual dashboard
    logbooks:
        title: Logbooks dashboard
    
modules:
    vessel_list:
        title: Vessels register
        icon: table
    vessel_breakdown:
        title: Vessels breakdown
        icon: ship
    vessel_qa:
        title: Vessels quality assessment
        icon: ship
    individual_list: 
        title: Individual list
    